# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2844e756a5506d907b7cf2232f6eeea005194478a5dc1f0976db0e48ff6dac43d2df72fc8323eafd5ef4f5a2b3d93077fb95c0504bd6c8fad660a990a071e13b

test:
  secret_key_base: 752ce0818b8261e4f970cbe8733345f6b3116b8179dabc00c58a7eeedea4285de07d666929cf9588008aeefcdd53a11bb54617e597f0ce48d1ffae342ac8bcc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
